"""GSK workbook catalog from MLR_Demo_Synthetic_Datasets_GSK.xlsx (Mock_Tickets).

Added on top of the existing TKT-1001 exam seed. Rule IDs match the spreadsheet.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta

from sqlalchemy.orm import Session

from app.core.enums import ChangeType, HitlGate
from app.models.rule import RuleDefinition
from app.models.ticket import Ticket


def seed_gsk_workbook_if_empty(db: Session) -> None:
    existing_ids = {r.rule_id for r in db.query(RuleDefinition).all()}
    from app.db.seed import _add_rule

    for spec in GSK_RULES:
        if spec["rule_id"] in existing_ids:
            continue
        _add_rule(db, **spec)
        existing_ids.add(spec["rule_id"])
    db.flush()

    have = {t.ticket_number for t in db.query(Ticket).all()}
    due = datetime.now(UTC) + timedelta(days=5)
    for row in GSK_TICKETS:
        if row["ticket_number"] in have:
            continue
        db.add(Ticket(due_date=due, is_demo_seed=True, status="RECEIVED", **row))
    for ticket in db.query(Ticket).filter(Ticket.hitl_gate.is_(None)).all():
        ticket.hitl_gate = HitlGate.GATE3_SINGLE_APPROVAL.value
        ticket.autonomy_tier = ticket.autonomy_tier or "Assisted"


GSK_RULES: list[dict] = [
    {
        "rule_id": "MB-US-TRE-001",
        "name": "US Trelegy promotional disclaimer",
        "rule_type": "TEXT",
        "category": "DISCLAIMER",
        "scope_type": "MARKET_BRAND",
        "body": {
            "rule_type": "TEXT",
            "rule_id": "MB-US-TRE-001",
            "field": "disclaimer",
            "scope": {"market": "US", "brand": "Trelegy", "therapeutic_area": "Respiratory"},
            "content": (
                "Trelegy Ellipta is indicated for maintenance treatment of COPD. "
                "This promotional claim is supported by the 2020 outcomes study (CIT-2020-001). "
                "See full prescribing information."
            ),
            "references": [{"type": "scientific_citation", "id": "CIT-2020-001"}],
            "flagged_terms": ["cure", "reverses lung damage"],
        },
        "market": "US",
        "brand": "Trelegy",
        "area": "Respiratory",
        "material": "Promotional",
        "versions": 2,
        "priority": 10,
    },
    {
        "rule_id": "MB-US-TRE-000",
        "name": "US Trelegy disclaimer (previous approved version)",
        "rule_type": "TEXT",
        "category": "DISCLAIMER",
        "scope_type": "MARKET_BRAND",
        "body": {
            "rule_type": "TEXT",
            "rule_id": "MB-US-TRE-000",
            "field": "disclaimer",
            "scope": {"market": "US", "brand": "Trelegy", "therapeutic_area": "Respiratory"},
            "content": "Trelegy Ellipta COPD maintenance disclaimer (prior approved wording, 2020 citation).",
            "references": [{"type": "scientific_citation", "id": "CIT-2020-001"}],
        },
        "market": "US",
        "brand": "Trelegy",
        "area": "Respiratory",
        "priority": 90,
    },
    {
        "rule_id": "MKT-US-002",
        "name": "US prescribing-information URL",
        "rule_type": "TEXT",
        "category": "PI_LINK",
        "scope_type": "MARKET",
        "body": {
            "rule_type": "TEXT",
            "rule_id": "MKT-US-002",
            "field": "pi_link",
            "scope": {"market": "US"},
            "content": "https://www.example-pi.gsk/us/en",
        },
        "market": "US",
        "material": "Promotional",
        "priority": 40,
    },
    {
        "rule_id": "MB-DE-TRE-001",
        "name": "DE Trelegy Pflichttext / PI-Link",
        "rule_type": "TEXT",
        "category": "PI_LINK",
        "scope_type": "MARKET_BRAND",
        "body": {
            "rule_type": "TEXT",
            "rule_id": "MB-DE-TRE-001",
            "field": "mandatory_text",
            "scope": {"market": "DE", "brand": "Trelegy"},
            "content": "Trelegy Ellipta Pflichttext DE. Fachinformation: https://www.example-pi.gsk/de/de",
        },
        "market": "DE",
        "brand": "Trelegy",
        "area": "Respiratory",
        "language": "DE",
        "priority": 15,
    },
    {
        "rule_id": "BRD-TRE-001",
        "name": "Trelegy brand restricted efficacy language",
        "rule_type": "TEXT",
        "category": "CLAIM",
        "scope_type": "BRAND",
        "body": {
            "rule_type": "TEXT",
            "rule_id": "BRD-TRE-001",
            "field": "claim",
            "scope": {"brand": "Trelegy"},
            "content": "Do not claim Trelegy reverses lung damage or is a cure.",
            "flagged_terms": ["reverses lung damage", "cure", "breakthrough"],
        },
        "brand": "Trelegy",
        "area": "Respiratory",
        "priority": 20,
    },
    {
        "rule_id": "MB-US-JEM-001",
        "name": "US Jemperli overall survival claim",
        "rule_type": "TEXT",
        "category": "CLAIM",
        "scope_type": "MARKET_BRAND",
        "body": {
            "rule_type": "TEXT",
            "rule_id": "MB-US-JEM-001",
            "field": "claim",
            "scope": {"market": "US", "brand": "Jemperli", "therapeutic_area": "Oncology"},
            "content": "Jemperli overall survival figure for US promotional use (current approved OS value).",
            "references": [{"type": "scientific_citation", "id": "CIT-2020-001"}],
        },
        "market": "US",
        "brand": "Jemperli",
        "area": "Oncology",
        "priority": 12,
    },
    {
        "rule_id": "SCI-003",
        "name": "Oncology scientific accuracy overlay",
        "rule_type": "TEXT",
        "category": "SCIENTIFIC_ACCURACY",
        "scope_type": "SCIENTIFIC_ACCURACY",
        "body": {
            "rule_type": "TEXT",
            "rule_id": "SCI-003",
            "field": "scientific_accuracy",
            "scope": {"therapeutic_area": "Oncology"},
            "content": "Oncology efficacy (OS/PFS) figures require current verified citation and scientific review.",
            "references": [{"type": "scientific_citation", "id": "CIT-2020-001"}],
        },
        "area": "Oncology",
        "priority": 5,
    },
    {
        "rule_id": "MB-JP-JEM-001",
        "name": "JP Jemperli routing",
        "rule_type": "LOGIC",
        "category": "ROUTING",
        "scope_type": "MARKET_BRAND",
        "body": {
            "rule_type": "LOGIC",
            "rule_id": "MB-JP-JEM-001",
            "scope": {"market": "JP", "brand": "Jemperli"},
            "when": {
                "all": [
                    {"field": "brand", "operator": "eq", "value": "Jemperli"},
                    {"field": "market", "operator": "eq", "value": "JP"},
                ]
            },
            "actions": [
                {"type": "route", "target": "Oncology Medical Review JP"},
                {"type": "flag", "value": "Local HA constraint"},
            ],
        },
        "market": "JP",
        "brand": "Jemperli",
        "area": "Oncology",
        "language": "JA",
        "priority": 15,
    },
    {
        "rule_id": "UNI-001",
        "name": "Universal restricted terms",
        "rule_type": "TEXT",
        "category": "CLAIM",
        "scope_type": "UNIVERSAL",
        "body": {
            "rule_type": "TEXT",
            "rule_id": "UNI-001",
            "field": "restricted_terms",
            "scope": {},
            "content": "Global restricted terms: cure, miracle, breakthrough cure.",
            "flagged_terms": ["cure", "miracle", "breakthrough cure"],
        },
        "priority": 80,
    },
    {
        "rule_id": "BRD-JEM-001",
        "name": "Jemperli brand restricted terms",
        "rule_type": "TEXT",
        "category": "CLAIM",
        "scope_type": "BRAND",
        "body": {
            "rule_type": "TEXT",
            "rule_id": "BRD-JEM-001",
            "field": "claim",
            "scope": {"brand": "Jemperli"},
            "content": "Jemperli brand restricted language includes breakthrough cure.",
            "flagged_terms": ["breakthrough cure", "cure"],
        },
        "brand": "Jemperli",
        "area": "Oncology",
        "priority": 25,
    },
    {
        "rule_id": "MB-BR-NUC-001",
        "name": "BR Nucala SAC number",
        "rule_type": "TEXT",
        "category": "LEGAL_FOOTER",
        "scope_type": "MARKET_BRAND",
        "body": {
            "rule_type": "TEXT",
            "rule_id": "MB-BR-NUC-001",
            "field": "sac_number",
            "scope": {"market": "BR", "brand": "Nucala"},
            "content": "Nucala Brasil SAC: 0800-000-0000",
        },
        "market": "BR",
        "brand": "Nucala",
        "area": "Respiratory",
        "language": "PT",
        "priority": 20,
    },
    {
        "rule_id": "MB-US-BLE-001",
        "name": "US Blenrep safety statement",
        "rule_type": "TEXT",
        "category": "DISCLAIMER",
        "scope_type": "MARKET_BRAND",
        "body": {
            "rule_type": "TEXT",
            "rule_id": "MB-US-BLE-001",
            "field": "safety_statement",
            "scope": {"market": "US", "brand": "Blenrep", "therapeutic_area": "Oncology"},
            "content": "Blenrep US safety statement. Boxed warning language must not be softened.",
        },
        "market": "US",
        "brand": "Blenrep",
        "area": "Oncology",
        "priority": 8,
    },
    {
        "rule_id": "MB-UK-SHI-001",
        "name": "UK Shingrix additional monitoring and URL",
        "rule_type": "TEXT",
        "category": "PI_LINK",
        "scope_type": "MARKET_BRAND",
        "body": {
            "rule_type": "TEXT",
            "rule_id": "MB-UK-SHI-001",
            "field": "additional_monitoring",
            "scope": {"market": "UK", "brand": "Shingrix"},
            "content": "Shingrix is subject to additional monitoring. PI: https://www.example-pi.gsk/uk/en/shingrix",
        },
        "market": "UK",
        "brand": "Shingrix",
        "area": "Vaccines",
        "priority": 18,
    },
    {
        "rule_id": "MKT-LATAM-001",
        "name": "LATAM fair-balance wording",
        "rule_type": "TEXT",
        "category": "DISCLAIMER",
        "scope_type": "MARKET",
        "body": {
            "rule_type": "TEXT",
            "rule_id": "MKT-LATAM-001",
            "field": "fair_balance",
            "scope": {"market": "LATAM"},
            "content": "LATAM fair-balance wording (current approved regional template).",
        },
        "market": "LATAM",
        "language": "ES",
        "priority": 35,
    },
    {
        "rule_id": "MB-FR-BEN-001",
        "name": "FR Benlysta adverse-event URL",
        "rule_type": "TEXT",
        "category": "PI_LINK",
        "scope_type": "MARKET_BRAND",
        "body": {
            "rule_type": "TEXT",
            "rule_id": "MB-FR-BEN-001",
            "field": "ae_url",
            "scope": {"market": "FR", "brand": "Benlysta"},
            "content": "https://www.example-ae.gsk/fr/benlysta",
        },
        "market": "FR",
        "brand": "Benlysta",
        "area": "Immunology",
        "language": "FR",
        "priority": 18,
    },
]


GSK_TICKETS: list[dict] = [
    {
        "ticket_number": "TCK-1001",
        "external_id": "SNOW-TRE-US-2026",
        "source_system": "SERVICENOW",
        "title": "US Trelegy disclaimer 2026 citation",
        "description": (
            "Update the US Trelegy promotional disclaimer to include the 2026 clinical trial citation "
            "and remove the 2020 study reference."
        ),
        "requester_name": "US Content Owner",
        "requester_email": "requester@mlr-ruleops.local",
        "priority": "HIGH",
        "market_hint": "US",
        "brand_hint": "Trelegy",
        "therapeutic_area_hint": "Respiratory",
        "language_hint": "EN",
        "change_type": ChangeType.TEXT_STRING_UPDATE.value,
        "risk_level": "LOW",
        "hitl_gate": HitlGate.GATE3_SINGLE_APPROVAL.value,
        "autonomy_tier": "Assisted",
        "expected_target_rule": "MB-US-TRE-001",
        "match_confidence": 0.98,
    },
    {
        "ticket_number": "TCK-1002",
        "external_id": "SNOW-US-PI-URL",
        "source_system": "SERVICENOW",
        "title": "Change PI URL for all US materials",
        "description": "Change the prescribing-information URL for all US promotional materials to the new corporate PI domain.",
        "requester_name": "US Regulatory",
        "requester_email": "regulatory@mlr-ruleops.local",
        "priority": "MEDIUM",
        "market_hint": "US",
        "brand_hint": None,
        "language_hint": "EN",
        "change_type": ChangeType.TEXT_STRING_UPDATE.value,
        "risk_level": "MEDIUM",
        "hitl_gate": HitlGate.GATE3_SINGLE_APPROVAL.value,
        "autonomy_tier": "Assisted",
        "expected_target_rule": "MKT-US-002",
        "match_confidence": 0.91,
    },
    {
        "ticket_number": "TCK-1003",
        "external_id": "JIRA-TRE-DE-PI",
        "source_system": "JIRA",
        "title": "DE Trelegy Pflichttext / PI-Link",
        "description": (
            "Bitte den Trelegy-Pflichttext und den Fachinformations-Link für Deutschland aktualisieren. "
            "Update Trelegy mandatory text and PI hyperlink in Germany (German request)."
        ),
        "requester_name": "DE Content Owner",
        "requester_email": "requester@mlr-ruleops.local",
        "priority": "MEDIUM",
        "market_hint": "DE",
        "brand_hint": "Trelegy",
        "therapeutic_area_hint": "Respiratory",
        "language_hint": "DE",
        "change_type": ChangeType.TEXT_STRING_UPDATE.value,
        "risk_level": "MEDIUM",
        "hitl_gate": HitlGate.GATE3_SINGLE_APPROVAL.value,
        "autonomy_tier": "Supervised",
        "expected_target_rule": "MB-DE-TRE-001",
        "match_confidence": 0.88,
    },
    {
        "ticket_number": "TCK-1004",
        "external_id": "SNOW-TRE-AMBIG",
        "source_system": "SERVICENOW",
        "title": "Update Trelegy disclaimer (market not specified)",
        "description": "Update the Trelegy disclaimer. Market was not specified on the ticket.",
        "requester_name": "Brand Team",
        "requester_email": "requester@mlr-ruleops.local",
        "priority": "MEDIUM",
        "market_hint": None,
        "brand_hint": "Trelegy",
        "change_type": ChangeType.AMBIGUOUS_INCOMPLETE.value,
        "risk_level": "MEDIUM",
        "hitl_gate": HitlGate.GATE2_RULE_MATCH.value,
        "autonomy_tier": "Supervised",
        "expected_target_rule": "AMBIGUOUS: MB-US-TRE-001 vs MB-DE-TRE-001 vs BRD-TRE-001",
        "match_confidence": 0.54,
    },
    {
        "ticket_number": "TCK-1005",
        "external_id": "SNOW-JEM-OS",
        "source_system": "SERVICENOW",
        "title": "US Jemperli overall survival figure",
        "description": "Update the US Jemperli overall survival figure used in promotional claims to the latest outcomes read-out.",
        "requester_name": "US Medical",
        "requester_email": "medical@mlr-ruleops.local",
        "priority": "HIGH",
        "market_hint": "US",
        "brand_hint": "Jemperli",
        "therapeutic_area_hint": "Oncology",
        "language_hint": "EN",
        "change_type": ChangeType.TEXT_STRING_UPDATE.value,
        "risk_level": "CRITICAL",
        "hitl_gate": HitlGate.GATE3_DUAL_APPROVAL.value,
        "autonomy_tier": "Escalated",
        "expected_target_rule": "MB-US-JEM-001 / SCI-003",
        "match_confidence": 0.86,
    },
    {
        "ticket_number": "TCK-1006",
        "external_id": "JIRA-JEM-JP-ROUTE",
        "source_system": "JIRA",
        "title": "Add Jemperli Japan routing rule",
        "description": (
            "Business logic change: if Jemperli is mentioned in Japan, route to Oncology Medical Review "
            "and flag the local health-authority constraint."
        ),
        "requester_name": "JP Brand Team",
        "requester_email": "requester@mlr-ruleops.local",
        "priority": "HIGH",
        "market_hint": "JP",
        "brand_hint": "Jemperli",
        "therapeutic_area_hint": "Oncology",
        "language_hint": "JA",
        "change_type": ChangeType.BUSINESS_LOGIC_CHANGE.value,
        "risk_level": "CRITICAL",
        "hitl_gate": HitlGate.GATE3_DUAL_APPROVAL.value,
        "autonomy_tier": "Escalated",
        "expected_target_rule": "MB-JP-JEM-001",
        "match_confidence": 0.90,
    },
    {
        "ticket_number": "TCK-1007",
        "external_id": "SNOW-UNI-CURE",
        "source_system": "SERVICENOW",
        "title": "Add breakthrough cure to global restricted terms",
        "description": "Add 'breakthrough cure' to the restricted-terms list globally (universal catalog and Jemperli brand overlay).",
        "requester_name": "Global Medical",
        "requester_email": "medical@mlr-ruleops.local",
        "priority": "HIGH",
        "market_hint": None,
        "brand_hint": "Jemperli",
        "change_type": ChangeType.TEXT_STRING_UPDATE.value,
        "risk_level": "HIGH",
        "hitl_gate": HitlGate.GATE3_SINGLE_APPROVAL.value,
        "autonomy_tier": "Supervised",
        "expected_target_rule": "UNI-001 / BRD-JEM-001",
        "match_confidence": 0.77,
    },
    {
        "ticket_number": "TCK-1008",
        "external_id": "JIRA-NUC-BR-SAC",
        "source_system": "JIRA",
        "title": "BR Nucala SAC number (Portuguese)",
        "description": (
            "Atualizar o número SAC do Nucala no Brasil. "
            "Update the Nucala SAC number for Brazil (Portuguese request)."
        ),
        "requester_name": "BR Content Owner",
        "requester_email": "requester@mlr-ruleops.local",
        "priority": "LOW",
        "market_hint": "BR",
        "brand_hint": "Nucala",
        "therapeutic_area_hint": "Respiratory",
        "language_hint": "PT",
        "change_type": ChangeType.TEXT_STRING_UPDATE.value,
        "risk_level": "LOW",
        "hitl_gate": HitlGate.GATE3_SINGLE_APPROVAL.value,
        "autonomy_tier": "Assisted",
        "expected_target_rule": "MB-BR-NUC-001",
        "match_confidence": 0.93,
    },
    {
        "ticket_number": "TCK-1009",
        "external_id": "SNOW-BLE-SOFTEN",
        "source_system": "SERVICENOW",
        "title": "Soften US Blenrep safety statement",
        "description": "Reword the US Blenrep safety statement to soften the tone for promotional use.",
        "requester_name": "US Brand Team",
        "requester_email": "requester@mlr-ruleops.local",
        "priority": "HIGH",
        "market_hint": "US",
        "brand_hint": "Blenrep",
        "therapeutic_area_hint": "Oncology",
        "language_hint": "EN",
        "change_type": ChangeType.TEXT_STRING_UPDATE.value,
        "risk_level": "HIGH",
        "hitl_gate": HitlGate.GATE3_BLOCK_RMCB.value,
        "autonomy_tier": "Escalated",
        "expected_target_rule": "MB-US-BLE-001",
        "match_confidence": 0.84,
    },
    {
        "ticket_number": "TCK-1010",
        "external_id": "JIRA-SHI-UK",
        "source_system": "JIRA",
        "title": "UK Shingrix additional monitoring and URL",
        "description": "Update the Shingrix additional-monitoring statement and PI URL in the UK.",
        "requester_name": "UK Medical",
        "requester_email": "medical@mlr-ruleops.local",
        "priority": "MEDIUM",
        "market_hint": "UK",
        "brand_hint": "Shingrix",
        "therapeutic_area_hint": "Vaccines",
        "language_hint": "EN",
        "change_type": ChangeType.TEXT_STRING_UPDATE.value,
        "risk_level": "MEDIUM",
        "hitl_gate": HitlGate.GATE3_SINGLE_APPROVAL.value,
        "autonomy_tier": "Assisted",
        "expected_target_rule": "MB-UK-SHI-001",
        "match_confidence": 0.89,
    },
    {
        "ticket_number": "TCK-1011",
        "external_id": "SNOW-LATAM-FB",
        "source_system": "SERVICENOW",
        "title": "LATAM fair-balance wording roll-out",
        "description": "Roll out the new fair-balance wording across LATAM markets.",
        "requester_name": "LATAM Brand Team",
        "requester_email": "requester@mlr-ruleops.local",
        "priority": "MEDIUM",
        "market_hint": "LATAM",
        "brand_hint": None,
        "language_hint": "ES",
        "change_type": ChangeType.TEXT_STRING_UPDATE.value,
        "risk_level": "MEDIUM",
        "hitl_gate": HitlGate.GATE2_RULE_MATCH.value,
        "autonomy_tier": "Supervised",
        "expected_target_rule": "MKT-LATAM-001 / UNI-001",
        "match_confidence": 0.61,
    },
    {
        "ticket_number": "TCK-1012",
        "external_id": "SNOW-VAGUE-1",
        "source_system": "SERVICENOW",
        "title": "Fix the disclaimer",
        "description": "fix the disclaimer, it's wrong.",
        "requester_name": "Unknown requester",
        "requester_email": "requester@mlr-ruleops.local",
        "priority": "LOW",
        "market_hint": None,
        "brand_hint": None,
        "change_type": ChangeType.AMBIGUOUS_INCOMPLETE.value,
        "risk_level": None,
        "hitl_gate": HitlGate.GATE1_INTENT_CONFIRM.value,
        "autonomy_tier": "Escalated",
        "expected_target_rule": "NONE - insufficient info",
        "match_confidence": 0.22,
    },
    {
        "ticket_number": "TCK-1013",
        "external_id": "JIRA-BEN-FR-AE",
        "source_system": "JIRA",
        "title": "FR Benlysta adverse-event URL",
        "description": (
            "Mettre à jour l'URL de déclaration des effets indésirables pour Benlysta en France. "
            "Update the Benlysta adverse-event reporting URL in France."
        ),
        "requester_name": "FR Regulatory",
        "requester_email": "regulatory@mlr-ruleops.local",
        "priority": "MEDIUM",
        "market_hint": "FR",
        "brand_hint": "Benlysta",
        "therapeutic_area_hint": "Immunology",
        "language_hint": "FR",
        "change_type": ChangeType.TEXT_STRING_UPDATE.value,
        "risk_level": "MEDIUM",
        "hitl_gate": HitlGate.GATE3_SINGLE_APPROVAL.value,
        "autonomy_tier": "Assisted",
        "expected_target_rule": "MB-FR-BEN-001",
        "match_confidence": 0.90,
    },
    {
        "ticket_number": "TCK-1014",
        "external_id": "SNOW-JEM-PFS",
        "source_system": "SERVICENOW",
        "title": "Change Jemperli PFS in scientific decks",
        "description": "Change the Jemperli progression-free survival (PFS) value used in scientific decks.",
        "requester_name": "US Medical",
        "requester_email": "medical@mlr-ruleops.local",
        "priority": "CRITICAL",
        "market_hint": "US",
        "brand_hint": "Jemperli",
        "therapeutic_area_hint": "Oncology",
        "language_hint": "EN",
        "change_type": ChangeType.TEXT_STRING_UPDATE.value,
        "risk_level": "CRITICAL",
        "hitl_gate": HitlGate.GATE3_BLOCK_RMCB.value,
        "autonomy_tier": "Escalated",
        "expected_target_rule": "SCI-003",
        "match_confidence": 0.81,
    },
    {
        "ticket_number": "TCK-1015",
        "external_id": "JIRA-TRE-RESTRICT",
        "source_system": "JIRA",
        "title": "Add reverses lung damage for US Trelegy",
        "description": "Add 'reverses lung damage' as an efficacy phrase for US Trelegy promotional materials.",
        "requester_name": "US Brand Team",
        "requester_email": "requester@mlr-ruleops.local",
        "priority": "HIGH",
        "market_hint": "US",
        "brand_hint": "Trelegy",
        "therapeutic_area_hint": "Respiratory",
        "language_hint": "EN",
        "change_type": ChangeType.TEXT_STRING_UPDATE.value,
        "risk_level": "HIGH",
        "hitl_gate": HitlGate.GATE3_BLOCK_RMCB.value,
        "autonomy_tier": "Escalated",
        "expected_target_rule": "BRD-TRE-001 (restricted)",
        "match_confidence": 0.79,
    },
    {
        "ticket_number": "TCK-1016",
        "external_id": "SNOW-TRE-ROLLBACK",
        "source_system": "SERVICENOW",
        "title": "Rollback US Trelegy disclaimer",
        "description": "Rollback the US Trelegy disclaimer to the previous approved version (MB-US-TRE-000).",
        "requester_name": "US Content Owner",
        "requester_email": "requester@mlr-ruleops.local",
        "priority": "MEDIUM",
        "market_hint": "US",
        "brand_hint": "Trelegy",
        "therapeutic_area_hint": "Respiratory",
        "language_hint": "EN",
        "change_type": ChangeType.ROLLBACK_REQUEST.value,
        "risk_level": "MEDIUM",
        "hitl_gate": HitlGate.GATE3_SINGLE_APPROVAL.value,
        "autonomy_tier": "Assisted",
        "expected_target_rule": "MB-US-TRE-001 -> MB-US-TRE-000",
        "match_confidence": 0.87,
    },
]
